### ISSUE TITLE
Otimize load users permissions

### ISSUE THREAD

**Issue by bsoliveira** [appzcoder/laravel-admin#1]
Thank you for the wonderful package. I would like to contribute a tip to optimize the loading of User permissions on AuthServiceProvider.

    public function boot(GateContract $gate)
    {
        // Checks table permissions exists
        if(!App::environment('local') && Schema::hasTable('permissions')){
            throw new \Exception("Table permissions not exists, please run migration!");            
        }

        parent::registerPolicies($gate);

......

**Comment by bsoliveira** [comment]
Oppss! fix =)

        if(App::environment('local') && !Schema::hasTable('permissions')){
            throw new \Exception("Table permissions not exists, please run migration!");            
        }

**Comment by bsoliveira** [comment]
I apologize for the many comments, after much trying got the final solution.

    /**
     * Register any application authentication / authorization services.
     *
     * @param  \Illuminate\Contracts\Auth\Access\Gate  $gate
     * @return void
     */
    public function boot(GateContract $gate)
    {
        // Checks table permissions exists in environment development
        if(App::environment('local')){
            if(Schema::hasTable('permissions')){
                $this->loadUserPermissions($gate);
            }
        }else{
            $this->loadUserPermissions($gate);
        }

        parent::registerPolicies($gate);

        // Granted all permission for admin users
        $gate->before(function ($user, $ability) {
            if ($user->hasRole('admin')) {
                return true;
            }
        });
    }

    protected function loadUserPermissions($gate)
    {
        // Dynamically register permissions with Laravel's Gate.
        $permissions = Permission::all();

        foreach ($permissions as $permission) {
            $gate->define($permission->name, function ($user) use ($permission) {
                return $user->hasPermission($permission);
            });
        }       
    }

**Comment by sohelamin** [comment]
Hi @bsoliveira 

Actually I didn't get what are you optimizing?
Are you checking the schema for local environment only or you're trying to optimize the loading time?

I'm not sure you noticed the file or not https://github.com/appzcoder/laravel-admin/blob/master/src/publish/Providers/AuthServiceProvider.php

If your solution is much optimized then please make a PR.

**Comment by bsoliveira** [comment]
Not a great optimization. The intention would be to reduce access to the database in production.

**Comment by bsoliveira** [comment]
Hi @sohelamin!

Thank you friend,  this really is not a good optimization. 

Today I had a mistake when cloning my project repository  and when running 'composer install' an error occurred because there was no file '.env' and therefore there was a configured database.

I believe that the best solution would enable an option in the configuration file such as: auto_register_permissions = true. by default false.

Thank you and I will continue monitoring the evolution of this wonderful package. 

*I apologize for my bad English, I am Brazilian and I speak little English. =)

**Comment by bsoliveira** [comment]
auth config file:
    'auto_register_permissions' => env('AUTO_REGISTER_PERMISSIONS', false),

Provider:

        // Dynamically register permissions with Laravel's Gate.
        if(config('auth.auto_register_permissions')){
            $permissions = Permission::all();

            foreach ($permissions as $permission) {
                $gate->define($permission->name, function ($user) use ($permission) {
                    return $user->hasPermission($permission);
                });
            }               
        }
