### ISSUE TITLE
Call to a member function hasRole() on null

### ISSUE THREAD

**Issue by ajiehatajie** [appzcoder/laravel-admin#10]
how to solve this, if the user is logged in yet,
 then this command I place right on the blade

layout.blade.php
`
  @if(Auth::user()->hasRole('superadmin'))
                   <li><a href="{{ url('/admin') }}">Admin Panel</a></li>
  @else
  
  @endif`

**Comment by sohelamin** [comment]
Just check auth first
```
if(Auth::check() && Auth::user()->hasRole('admin')) {
    // Do admin stuff here
} else {
    // Do nothing
}
```
