### ISSUE TITLE
How can I use multi roles on route middleware

### ISSUE THREAD

**Issue by jatiyanon** [appzcoder/laravel-admin#11]
First, your app are simple and awesome.

BUT
`Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'roles'], 'roles' => ['admin','user']], function () {
	Route::get('/', ['uses' => 'Admin\AdminController@index']);
});`
you will see `'roles' => ['admin','user']`
it doesn't work, how can I set the route group for admin, user role ?

**Comment by jatiyanon** [comment]
In `HasRoles.php` in `function hasRole`,  I changed  `return !!$role->intersect($this->roles)->count();` to

```
if (is_array($role)) {
            foreach ($role as $role_r) {
                if ($this->hasRole($role_r)) {
                    return true;
                }
            }
            return false;
 }
return (bool) $role->intersect($this->roles)->count();
```
Absolutely Good!

**Comment by aliabdzad** [comment]
+1
