### ISSUE TITLE
Protect "Generator" from non-admin

### ISSUE THREAD

**Issue by Sengchheang** [appzcoder/laravel-admin#13]
Hi, 

I am trying to protect all dashboard links (/admin/*) from being accessible by non-admin.
So far, the code below can get the job done.

/routes/web.php
```
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'roles'], 'roles' => 'admin'], function () {
	Route::get('/', 'Admin\AdminController@index');
	Route::get('/give-role-permissions', 'Admin\AdminController@getGiveRolePermissions');
	Route::post('/give-role-permissions', 'Admin\AdminController@postGiveRolePermissions');
	Route::resource('/roles', 'Admin\RolesController');
	Route::resource('/permissions', 'Admin\PermissionsController');
	Route::resource('/users', 'Admin\UsersController');
});
```

There is the link 'admin/generator' which can be accessed publicly and it seems like there is some protection already in  https://github.com/appzcoder/laravel-admin/blob/master/src/routes.php, but unfortunately it did not work in my case.

Can anyone give me hint how to get this done?

(FYI: I started Laravel a few days ago, so I am very beginner. Thank for your patience)

Regarding to this issue, my other thinking is that I made mistake at the first place which I installed this package by using composer require but not require-dev.  But I do need the dashboard functions.

Thank for any answers

**Comment by sohelamin** [comment]
Hi @Sengchheang 

I've put the route into main route so you can change it anytime. Comited at fd59b70

**Comment by Sengchheang** [comment]
Thank you @sohelamin 
The change works like magic.
