### ISSUE TITLE
Error Form-Field

### ISSUE THREAD

**Issue by vik0803** [appzcoder/laravel-admin#14]
Hi,

There is an error when using CRUD Generator - On Post event I believe that it is trying to search for FORM-FIELD.blade.stab file whereas there is no folder "form-fields". 

File does not exist at path /var/www/html/app/test/resources/crud-generator/form-fields/form-field.blade.stub

Appreciate if you can help with these.

Thanks,
Vik

**Comment by sohelamin** [comment]
Hi @vik0803 ,

I could not found any issue at all.
Did you follow the installation command?
eg. `php artisan laravel-admin:install'

Let me know if you still get stuck.

**Comment by GregoryHGS** [comment]
I also encountered this issue.

**Comment by sohelamin** [comment]
Sorry guys it was my fault I did not add the stuff when updated the `crud-generator` package.
Fixed at 0b580ad

Please let me know if you're still having any issues.
