### ISSUE TITLE
install error in laravel 5.1

### ISSUE THREAD

**Issue by ozasan** [appzcoder/laravel-admin#15]
exec `php artisan laravel-admin:install`

make:auth not found error.(make:auth is laravel 5.2 or later)

vendor/appzcoder/laravel-admin/src/LaravelAdminCommand.php
line 73: $this->call('make:auth');

Please forgive me my lousy English.
Thanks.

**Comment by sohelamin** [comment]
Hi @ozasan 

I've made a fix at f3a3122

**Comment by ozasan** [comment]
Hi @sohelamin 

Thank you for fix!!
