### ISSUE TITLE
doesn't work in Laravel 5.4

### ISSUE THREAD

**Issue by mrkatz** [appzcoder/laravel-admin#16]
Your package will not install alongside laravel 5.4.x-dev.

**Comment by sohelamin** [comment]
@mrkatz I've tried with 5.4 nothing wrong.
Can you let me know if you still having the issue?

**Comment by Sengchheang** [comment]
Just upgraded to laravel v5.4 this morning and everything is running just fine.

A few step to note:

```
composer update  appzcoder/laravel-admin
php artisan cache:clear; php artisan config:clear; php artisan route:clear; php artisan view:clear;
```

**Comment by janareit** [comment]
I used L 5.4.15 and install worked perfectly.
