### ISSUE TITLE
Error Extending for multitenancy 

### ISSUE THREAD

**Issue by elemes1** [appzcoder/laravel-admin#17]
Hi. 

Thank you for the good work. 
i tried extending the app for multitenancy and modifying the schema.  I get error after changing the table name 
``SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tracker.role_user' doesn't exist (SQL: select `RG_roles`.*, `role_user`.`user_id` as `pivot_user_id`, `role_user`.`role_id` as `pivot_role_id` from `RG_roles` inner join `role_user` on `RG_roles`.`id` = `role_user`.`role_id` where `role_user`.`user_id` = 1)``

**Comment by sohelamin** [comment]
@elemes1 This issue is not related to the package.
You're free to use the model as you want even you can customize the model controller.

**Comment by elemes1** [comment]
Thanks @sohelamin  had to revert back to the previous Schema.
