### ISSUE TITLE
Select dropdown role option selected in edit users

### ISSUE THREAD

**Issue by juanjose75** [appzcoder/laravel-admin#18]
do not see the selected roles when I edit the user.

View resources\views\admin\users\form.blade.php line 27

I changed it for " <option value="{{ $role->name }}" **{{ isset($user_roles)?(in_array($role->name, $user_roles) ? 'selected="selected"' : ''):'' }}**>{{ $role->label }}</option> "

**Comment by sohelamin** [comment]
Fixed at ba4e3ac
