### ISSUE TITLE
Class 'App\User' not found

### ISSUE THREAD

**Issue by emiliosa** [appzcoder/laravel-admin#23]
Step 5: Install the admin package.
`php artisan laravel-admin:install`

Result:

> PHP Fatal error:  Class 'App\User' not found in /var/www/html/inversiones/vendor/appzcoder/laravel-admin/src/LaravelAdminCommand.php on line 44
>                                                            
> [Symfony\Component\Debug\Exception\FatalErrorException]  
> Class 'App\User' not found

Does i need User.php file in Model directory?

**Comment by sohelamin** [comment]
@emiliosa You should have a model `App\User`
