### ISSUE TITLE
php artisan laravel-admin:install not work in laravel 5.4

### ISSUE THREAD

**Issue by Rahul-pra** [appzcoder/laravel-admin#24]
I am using 

> php artisan laravel-admin:install 
 I  got following error  but database migration perfectly work 
![screenshot from 2017-03-03 13 04 00](https://cloud.githubusercontent.com/assets/17510537/23545993/a9c479ac-0023-11e7-90f4-2df1e1c3a9d3.png)
NOTE: Database connection and .env connection right and migrations,password_resets and users table created

**Comment by sohelamin** [comment]
@Rahul-pra You maybe using the latest utf8mb4 character set.
Set default string length for migration on `AppServiceProvider` 
```
use Illuminate\Support\Facades\Schema;

/**
 * Bootstrap any application services.
 *
 * @return void
 */
public function boot()
{
    Schema::defaultStringLength(191);
}
```

**Comment by Rahul-pra** [comment]
@appzcoder/laravel-admin

Thanks you are right. I solve my problem as per your suggestion but CSS 
file not load how can solve this let me know..
