### ISSUE TITLE
PHP Fatal error:  Trait 'App\HasRoles' not found

### ISSUE THREAD

**Issue by ajiehatajie** [appzcoder/laravel-admin#25]
if run this command 
php artisan laravel-admin:install

error  
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Trait 'App\HasRoles' not found

solved if run php artisan vendor:publish

**Comment by sohelamin** [comment]
You need to follow the instructions step by step.
https://github.com/appzcoder/laravel-admin#installation
