### ISSUE TITLE
Config your database first

### ISSUE THREAD

**Issue by shakeelcse09** [appzcoder/laravel-admin#31]
everything is ok upto i hit $ php artisan laravel-admin:install
after creating database on phpmyadmin when i hit this command it says:

"Config your database first"

**Comment by sohelamin** [comment]
@shakeelcse09 check your database connection without this package.
There might be causing any error with your database.
In order to checking you can run `php artisan migrate` command

**Comment by shakeelcse09** [comment]
solved this but right now after install and when creating crud its telling on laravel 5.2.*

FatalThrowableError in CrudControllerCommand.php line 76:
Call to undefined method Appzcoder\CrudGenerator\Commands\CrudControllerCommand::qualifyClass()
