### ISSUE TITLE
exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::assignRole()

### ISSUE THREAD

**Issue by fgvicente** [appzcoder/laravel-admin#32]
Problem when add user.

exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::assignRole()' 
in /var/www/html/uno/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2451

**Comment by godxavia** [comment]
Solution?

**Comment by sohelamin** [comment]
Did you use HasRoles trait in User model?
