### ISSUE TITLE
where is it /js/app.js & /css/app.css ?

### ISSUE THREAD

**Issue by zizou86** [appzcoder/laravel-admin#4]
Hi,

/js/app.js & /css/app.css not found after installation.

**Comment by karneaud** [comment]
I'm assuming this makes it easy to add AngularJS into your package?

**Comment by zizou86** [comment]
How ?
I must add AngularJs ?

**Comment by sohelamin** [comment]
@zizou86 You can use app.js & app.css of the main application.
So you don't need to put these files into the package and the package publish it's assets to the application. 
So once you've published the asset if you can decouple the package from main app.

**Comment by sohelamin** [comment]
@karneaud replied to this #5

**Comment by zizou86** [comment]
I have published but app.js doesn't appear

**Comment by zizou86** [comment]
also app.css

**Comment by sohelamin** [comment]
The package use the both files from the application.
eg: publice/js/app.js, publice/css/app.css
Which laravel version are you using now?

**Comment by zizou86** [comment]
5.2.*

publice/js/app.js, publice/css/app.css not found.

**Comment by zizou86** [comment]
any response !

**Comment by sohelamin** [comment]
@zizou86 you can add your own.

If you even don't know how to do it then just replace app.css with
```
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
```
And remove the app.js file
