### ISSUE TITLE
Why cannot open "admin/*/create" page ?

### ISSUE THREAD

**Issue by minoryorg** [appzcoder/laravel-admin#41]
I installed laravel-admin in Laravel 5.5
I confirmed that I can "view", "edit", "delete" actions and show list.
but, "create" is not working.
When I click the "Add New" button, I see a message like this
"Sorry, the page you are looking for could not be found."
404 not found error ?

**Comment by minoryorg** [comment]
This is a bug in Laravel 5.5.
Thanks.

**Comment by sohelamin** [comment]
@minoryorg Okay,
I was trying to reproduce but everything seems fine here.
