### ISSUE TITLE
[MariaDB] Laravel Specific Key Was Too Long

### ISSUE THREAD

**Issue by rognoni** [appzcoder/laravel-admin#42]
Executing the command `php artisan laravel-admin:install` you have this error:
```
1071 Specified key was too long; max key length is 767 bytes
```

This is the solution:
```php
namespace App\Providers;

use Illuminate\Support\Facades\Schema;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        //
        Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```

**Comment by goszowski** [comment]
You must use a newer mysql version.

**Comment by cfioretti** [comment]
I had the same problem with latest version of Mariadb. I solved it in this way.

**Comment by sohelamin** [comment]
Guys there is nothing to do with this package. You need to solve by your own.

**Comment by LarryTX** [comment]
"Guys there is nothing to do with this package. You need to solve by your own." You must be dedicated to sending people running away from Laravel and to Yii2 where there is at least some support. This says, "Don't expect any support whatsoever to develop in Laravel." Developers the world over use Xampp which for extremely good and totally excellent reasons ditched Oracle MySQL like the dirt it is and went to MariaDB, the only one of the two acceptable to the Open Source community.

After years developing in Yii2, I decided to try Laravel. Now, I'm totally turned off. Oh well, just a little time wasted. Back to Yii2.
