### ISSUE TITLE
[Suggestion] Move "Give Role Permissions" into "Roles" using multiple select

### ISSUE THREAD

**Issue by rognoni** [appzcoder/laravel-admin#45]
![laravel-admin_permissions.png](https://gist.githubusercontent.com/rognoni/e3e91337bbe86dffde1d1a8c46ec7110/raw/08b92f4e4eeebed358182a6f4a2b6cb7b9a4651e/laravel-admin_permissions.png)

**Comment by sohelamin** [comment]
Okay will update on the next release
