### ISSUE TITLE
Can not select multiple permission

### ISSUE THREAD

**Issue by HamidOsouli** [appzcoder/laravel-admin#47]
We can not select multiple options when we use  givePermissionTo method like this :
```
 public function givePermissionTo(Permission $permission)
    {
        return $this->permissions()->save($permission);
    }
```
as you can see, we typehint the injection to Permission..

**Comment by sohelamin** [comment]
For now you can give once permission with this method call. If you want to give multiple permissions then you should call multiple times.
And if you want to improve feel free to contribute :)
