### ISSUE TITLE
Angular JS

### ISSUE THREAD

**Issue by karneaud** [appzcoder/laravel-admin#5]
Came across your project and was wondering how easy would it be to integrate AngularJS into this project?

**Comment by sohelamin** [comment]
Yeah you can use Angular JS.
For this you just need to publish the assets once you've done you can do what ever you want without the package.
But the package will help you to generate the CRUD.

You can check it out https://github.com/sohelamin/laravel-starter
Here I've used Vue.js

**Comment by karneaud** [comment]
@sohelamin aaahhhh.... nice i'm sort of  a VueJS man myself :-) . If I use your starter-kit would I still need to install this package?

**Comment by sohelamin** [comment]
No you don't need this package anymore if you want to use the starter.
