### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by Omegatcu** [appzcoder/laravel-admin#51]
I use a lot more Bootstrap 4 these days - if I modify the Templates would you add them to this Project?
This way we would have BS4 options for Building Admin Panels

**Comment by dexit** [comment]
Could please share those templates?

**Comment by sohelamin** [comment]
We need to sort out it on `appzcoder/crud-generator` package

**Comment by sohelamin** [comment]
Guys, Please use the new update to use the bootstrap 4
