### ISSUE TITLE
permision controller method store and update less with in flash message

### ISSUE THREAD

**Issue by ajiehatajie** [appzcoder/laravel-admin#52]
`Parse error: syntax error, unexpected '(', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'`

`/Users/hatajie/Sites/isidia-backend/app/Http/Controllers/Admin/PermissionsController.php
     */
    public function create()
    {
        return view('admin.permissions.create');
    }
 
    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return void
     */
    public function store(Request $request)
    {
        $this->validate($request, ['name' => 'required']);
 
        Permission::create($request->all());
 
        return redirect('admin/permissions')->('flash_message', 'Permission added!');
    }`

method store and update less with in flash message
solved with 
`return redirect('admin/permissions')->with('flash_message','Permission added !');
`

and error again 
`Undefined variable: role (View: /Users/hatajie/Sites/isidia-backend/resources/views/admin/roles/form.blade.php) (View: /Users/hatajie/Sites/isidia-backend/resources/views/admin/roles/form.blade.php)`

**Comment by sohelamin** [comment]
Fixed will release a hot fix soon
