### ISSUE TITLE
Composer install fails with latest crud-generator

### ISSUE THREAD

**Issue by buethling** [appzcoder/laravel-admin#54]
This tool looks great but I am not able to install it with composer as I've already installed your latest crud-generator (which works great), which is at ^3.0.

Error:
>Problem 1
>appzcoder/laravel-admin v1.0.4 requires appzcoder/crud-generator ^2.0 -> satisfiable by >appzcoder/crud-generator[2.0.x-dev, v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4, v2.0.5, v2.0.6, v2.0.7, v2.0.8] but >these conflict with your requirements or minimum-stability.

**Comment by sohelamin** [comment]
We're updating this package and will release a new version soon.
Meanwhile, you use from develop branch to solve your issue `composer require appzcoder/laravel-admin:dev-develop`
