### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by diorz38** [appzcoder/laravel-admin#55]
When i try to install for laravel 5.3:
step:
- fresh instal laravel 5.3
- install the packcage through composer
- add config in config/app.
- dumpautoload
- set db connection in env
- run php artisan laravel-admin:install (this when i got an error)

it got an error:

php artisan laravel-admin:install

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Appzcoder\LaravelAdmin\LaravelAdminServiceProvider' not found

i cant even publish the package..

what do i wrong?

**Comment by sohelamin** [comment]
Did you follow https://github.com/appzcoder/laravel-admin#for-laravel--55-you-need-to-follow-these-steps-1 for older laravel?
