### ISSUE TITLE
Password is required to edit form

### ISSUE THREAD

**Issue by alexeydg** [appzcoder/laravel-admin#58]
Pls fix:
users/create.blade.php  @include ('admin.users.form', ['submitButtonText' => 'Update'])  ---> @include ('admin.users.form', ['passwordRequired' => true,'submitButtonText' => 'Update'])

users/edit.blade.php @include ('admin.users.form', ['submitButtonText' => 'Update'])  ---> @include ('admin.users.form', ['passwordRequired' => false, 'submitButtonText' => 'Update'])

users/form.blade.php Row 18 
{!! Form::password('password', ['class' => 'form-control', **'required' => $passwordRequired** ? 'required' : false]) !!}

**Comment by sohelamin** [comment]
Will get you soon
