### ISSUE TITLE
Not Working in php 7.0

### ISSUE THREAD

**Issue by AmirJavaidSwe** [appzcoder/laravel-admin#61]
Hi,
I installed a fresh new laravel 5.5 version and installed this packge by composer command and php artisan laravel-admin:install.

After installing when I run application, even run laravel default route of welcome page, aplication is giving this error,

```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_PARSE)
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)
```

Kindly look into this issue, or guide how can i resolve this

**Comment by mikeerickson** [comment]
@AmirJavaidSwe Have a look at this thread (it is a common issue and this describes the issue and supported fix)

https://github.com/laravel/framework/issues/23537

**Comment by AmirJavaidSwe** [comment]
@mikeerickson Dear I was there before you suggested me to this thread, for once you can check it by yourself.

**Comment by mikeerickson** [comment]
@amirJavaidSwe I am sorry, but I don’t understand your response? If you could please clarify, I would be happy to assist

**Comment by vickygillsf** [comment]
@AmirJavaidSwe its not issue of the this package issue is from PHP version as nullable return types are not in PHP 7.0 , Nullable return types are introduce in PHP 7.1.3 , update your PHP version to fix this issue.
