### ISSUE TITLE
where is the 'laravelAdminMenus' variable defined ?

### ISSUE THREAD

**Issue by sanhar** [appzcoder/laravel-admin#63]
Well.. 

in admin dashboard , sidebar.blade.php has 'laravelAdminMenus' variable. 

I would like to figure out where the variable  start  and what contains. 

I searched whole source  but failed to find out. 

Where is if from ?

**Comment by hundra** [comment]
@sanhar did you find out where it is defined? I can find the menus.json file, but I do not understand how the variable $laravelAdminMenus gets set
