### ISSUE TITLE
Add support for Laravel 6.x?

### ISSUE THREAD

**Issue by tuan930929** [appzcoder/laravel-admin#73]
I try to install this package in Laravel 6.2, but it cannot.

**Comment by dukenst2006** [comment]
Please add support for laravel 6

**Comment by blueblazerchrist** [comment]
please add support for laravel 6.X

**Comment by kierenblack** [comment]
Will there be support for laravel 6 soon?

**Comment by vimalmistry** [comment]
Any update ??

**Comment by recci** [comment]
Agreed!

**Comment by vimalmistry** [comment]
Hello Everyone.
If you want to use it in laraval 6.x I forked repository

https://github.com/vimalmistry/laravel-admin

Instructions are same just added one step. read it carefully

**Comment by sohelamin** [comment]
Can you guys check now?

**Comment by recci** [comment]
"make:auth" is not defined

**Comment by recci** [comment]
also fails on 5.8.37

**Comment by BooJoe** [comment]
I cant get it to work either.

**Comment by BooJoe** [comment]
> Any update ??



> Hello Everyone.
> If you want to use it in laraval 6.x I forked repository
> 
> https://github.com/vimalmistry/laravel-admin
> 
> Instructions are same just added one step. read it carefully

Think we need a bit more info. Where do you define the repository?

**Comment by louisdj** [comment]
> > Any update ??
> 
> > Hello Everyone.
> > If you want to use it in laraval 6.x I forked repository
> > https://github.com/vimalmistry/laravel-admin
> > Instructions are same just added one step. read it carefully
> 
> Think we need a bit more info. Where do you define the repository?

You should add it into the composer.json file

**Comment by sohelamin** [comment]
Hi Guys,
 Sorry for the delay update. This package will work on Laravel 6 & 7
