### ISSUE TITLE
Call to undefined function snake_case()

### ISSUE THREAD

**Issue by diegomagikal** [appzcoder/laravel-admin#79]
Hello,

I'm using a fresh installation from laravel 7 and laravel-admin v3.3.0. When I use the Generator in tools box, i get this error:

`Call to undefined function Appzcoder\LaravelAdmin\Controllers\snake_case()`

**Comment by multiarts** [comment]
Here, too, the same thing happens.

Larave 7.x fresh installation.

**Comment by tahitahi** [comment]
same here

**Comment by multiarts** [comment]
> > Here, too, the same thing happens.
> > Larave 7.x fresh installation.
> 
> Solved:
> Edit on vendor \appzcoder\laravel-admin\src\Controllers\ProcessController.php
> 
> Add **_use Illuminate\Support\Str;_**
> 
> Change snake_case for Str::snake
> 
> `$routeName = ($commandArg['--route-group']) ? $commandArg['--route-group'] . '/' . Str::snake($name, '-') : Str::snake($name, '-');`

Solution.
