### ISSUE TITLE
This project is creating more problem then solving problem

### ISSUE THREAD

**Issue by depixedprojects** [appzcoder/laravel-admin#80]
I used this package a lot since last 3+ years. but recently after realising laravel 7 it is frustrating and creating more problem then solve problem. Like recently in laravel 8 i can not install another packages because this package have some version issue.  I can not imagine my project without this package.

I am not expecting greatness. But at least do some document changes for version specific. if you are not going to maintain frequently.

**Comment by sohelamin** [comment]
A new version has been released.
And always welcome to PR :)
