### ISSUE TITLE
Facing error while installing another package or update

### ISSUE THREAD

**Issue by vimalmistry** [appzcoder/laravel-admin#81]
I am using Laravel 7.

![Screenshot 2020-10-02 at 8 51 36 AM](https://user-images.githubusercontent.com/3993163/94884987-99f78480-048c-11eb-9dd7-79ff0aa2a32c.png)

![Screenshot 2020-10-02 at 8 51 28 AM](https://user-images.githubusercontent.com/3993163/94884995-9fed6580-048c-11eb-80ca-b1623a0d0fa5.png)

**Comment by georgechitechi** [comment]
Facing same issue. Tried in Laravel 6 and 8 same error
