### ISSUE TITLE
Call to undefined relationship [roles] on model [User]

### ISSUE THREAD

**Issue by azzozhsn** [appzcoder/laravel-admin#9]
After install it on laravel 5.3 when I try to edit a user I get this error:

RelationNotFoundException in RelationNotFoundException.php line 20:
Call to undefined relationship [roles] on model [App\User].

**Comment by azzozhsn** [comment]
Also after I added the roles() relationship, when I try to assin roles to user I get this error:

BadMethodCallException in Builder.php line 2448:
Call to undefined method Illuminate\Database\Query\Builder::assignRole()

**Comment by sohelamin** [comment]
Did you follow the installation instructions https://github.com/appzcoder/laravel-admin#installation ?
eg: step-6
```User``` model should have a ```HasRoles``` trait

**Comment by azzozhsn** [comment]
Apparently I forgot step 6. Thank you, it is an amazing work.
